# Description:
#   j2cl/vmbootstrap: The third layer of JS utility functions.
#
# Depends on the JRE JS.

package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

js_library(
    name = "vmbootstrap",
    srcs = glob(["**/*.js"]),
)
