package(
    default_applicable_licenses = ["//:j2cl_license"],
    default_visibility = ["//transpiler/javatests/com/google/j2cl/integration/java/j2ktiosinterop:__subpackages__"],
    licenses = ["notice"],
)
