package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

java_library(
    name = "errors",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/common/collect",
    ],
)
