package(licenses = ["notice"])

java_test(
    name = "SourceUtilsTest",
    srcs = ["SourceUtilsTest.java"],
    deps = [
        "//third_party:junit",
        "//third_party:truth",
        "//transpiler/java/com/google/j2cl/common",
    ],
)
