package(
    default_applicable_licenses = ["//:j2cl_license"],
    default_visibility = ["//transpiler/javatests/com/google/j2cl/readable:__subpackages__"],
    licenses = ["notice"],
)

filegroup(
    name = "conformance_proto",
    srcs = ["conformance_proto.txt"],
)

filegroup(
    name = "diff_check",
    srcs = ["diff_check.sh"],
)
