package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

load(
    "/third_party/java_src/j2cl/build_def/j2cl_java_library",
    "j2cl_java_library",
)

j2cl_java_library(
    name = "bar_lib",
    srcs = ["Bar.java"],
)
