package(default_visibility = ["//:__subpackages__"])

# Apache2
licenses(["notice"])

java_library(
    name = "sourcemap",
    srcs = glob(["*.java"]),
    deps = [
        "//transpiler/java/com/google/j2cl/ast/common",
        "//transpiler/java/com/google/j2cl/common",
    ],
)
