load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

package(
    default_applicable_licenses = ["//:j2cl_license"],
    licenses = ["notice"],
)

sh_binary(
    name = "deploy",
    srcs = ["deploy.sh"],
)
