/**
 * As we are not running the transpiler, this file is hand rolled as a mock.
 * It  mocks the ClassWithNativeMethod class by creating
 * a constructor function with the same name.
 * The code generated by the converter will be able to
 * add functions to this prototype afterwards.
 */
var ClassWithNativeMethod = function() {};
ClassWithNativeMethod.$clinit = function() {};
