# Google owns the copyright
licenses(["unencumbered"])

js_library(
    name = "A-native",
    srcs = [
        "a-native.js",
    ],
    deps = [
        "//javascript/closure:base",
    ],
)

js_library(
    name = "ajd",
    deps_mgmt = "closure",
    deps = [
        ":C",
    ],
)
