package(licenses = ["notice"])

py_library(
    name = "repo_util",
    srcs = ["repo_util.py"],
    visibility = ["//transpiler/javatests/com/google/j2cl/integration:__pkg__"],
)

py_library(
    name = "wat_util",
    srcs = ["wat_util.py"],
    visibility = ["//transpiler/javatests/com/google/j2cl/readable/minion:__pkg__"],
)
