load("//third_party/bazel_rules/rules_python/python:py_library.bzl", "py_library")

package(
    default_applicable_licenses = ["//:j2cl_license"],
    licenses = ["notice"],
)

py_library(
    name = "repo_util",
    srcs = ["repo_util.py"],
    visibility = ["//transpiler/javatests/com/google/j2cl/integration:__pkg__"],
)
