# Description:
#   j2cl tests verifying important optimizations

package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

load("j2cl_optimization_test", "j2cl_optimization_test")

j2cl_optimization_test(
    name = "BooleansTest",
)

j2cl_optimization_test(
    name = "StringsTest",
)
