load("@rules_java//java:defs.bzl", "java_library")

package(
    default_applicable_licenses = ["//:j2cl_license"],
    licenses = ["notice"],
)

java_library(
    name = "profiler",
    srcs = ["Profiler.java"],
    visibility = ["//transpiler/java/com/google/j2cl/common/bazel:__pkg__"],
)
