/**
 * As we are not running the transpiler, this file is hand rolled as a mock.
 * It mocks the Outer$Inner and Outer$Inner$Inner
 * classes by creating respectively constructor function with
 * the same name.
 * The code generated by the converter will be able to
 * add functions to these prototype afterwards.
 */
var Outer$Inner = function() {};
var Outer$Inner$InnerInner = function() {};
