package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

java_library(
    name = "visitors",
    srcs = glob(["*.java"]),
    deps = ["//transpiler/java/com/google/j2cl/ast"],
)
