package(default_visibility = [
    "//third_party/java/j2cl:__pkg__",
    "//:__subpackages__",
])

# Google owns the copyright
licenses(["unencumbered"])

java_library(
    name = "rerunning_transpiler",
    srcs = ["RerunningJ2clTranspiler.java"],
    deps = [
        "//transpiler/java/com/google/j2cl/errors",
        "//transpiler/java/com/google/j2cl/transpiler",
    ],
)
