/*
 * Copyright 2026 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.j2cl.transpiler;

import com.google.errorprone.annotations.FormatMethod;
import com.google.errorprone.annotations.FormatString;
import java.io.IOException;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/** A simple annotation processor for testing. */
@SupportedAnnotationTypes("com.google.j2cl.transpiler.TestAnnotation")
public class TestAptProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    for (var element : roundEnv.getElementsAnnotatedWith(TestAnnotation.class)) {
      // Test that APT options are forwarded by J2CL.
      if (!processingEnv.getOptions().containsKey("TestAptProcessor.enabled")) {
        throw new RuntimeException("TestAptProcessor.enabled is not set");
      }

      var name = "Generated" + element.getSimpleName();
      var packageName =
          ((PackageElement) element.getEnclosingElement()).getQualifiedName().toString();

      writeSourceFile(
          packageName,
          name,
          """
          package %s;
          import jsinterop.annotations.JsMethod;
          // Generated by TestAptProcessor.java
          public class %s {
            @JsMethod
            public static native void foo();
          }
          """,
          packageName,
          name);

      writeResourceFile(packageName, name + ".native.js", "// Empty native.js file.");

      if (processingEnv.getOptions().containsKey("TestAptProcessor.generateJsSource")) {
        writeResourceFile(packageName, name + ".js", "// Plain .js file generated by APT.");
      }
    }
    return false;
  }

  @Override
  public SourceVersion getSupportedSourceVersion() {
    return SourceVersion.latestSupported();
  }

  @FormatMethod
  private void writeSourceFile(
      String packageName, String fileName, @FormatString String format, Object... args) {
    try {
      writeFile(
          processingEnv.getFiler().createSourceFile(packageName + "." + fileName), format, args);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  @FormatMethod
  private void writeResourceFile(
      String packageName, String fileName, @FormatString String format, Object... args) {
    try {
      writeFile(
          processingEnv
              .getFiler()
              .createResource(StandardLocation.SOURCE_OUTPUT, packageName, fileName),
          format,
          args);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  @FormatMethod
  private static void writeFile(FileObject file, @FormatString String format, Object... args)
      throws IOException {
    try (var writer = file.openWriter()) {
      writer.write(String.format(format, args));
    }
  }
}
