/*
 * Copyright 2026 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.j2cl.transpiler;

import java.io.IOException;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;

/** A simple annotation processor for testing. */
@SupportedAnnotationTypes("com.google.j2cl.transpiler.TestAnnotation")
public class TestAptProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    for (var element : roundEnv.getElementsAnnotatedWith(TestAnnotation.class)) {
      var name = "Generated" + element.getSimpleName();
      var packageName =
          ((PackageElement) element.getEnclosingElement()).getQualifiedName().toString();

      try {
        var generatedSourceFile =
            processingEnv.getFiler().createSourceFile(packageName + "." + name);
        var writer = generatedSourceFile.openWriter();
        writer.write(
            String.format(
                """
                package %s;
                // Generated by TestAptProcessor.java
                public class %s {}
                """,
                packageName, name));
        writer.close();
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }
    return false;
  }

  @Override
  public SourceVersion getSupportedSourceVersion() {
    return SourceVersion.latestSupported();
  }
}
