/*
 * Copyright 2026 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.j2cl.transpiler;

import com.google.errorprone.annotations.FormatMethod;
import com.google.errorprone.annotations.FormatString;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/** A simple annotation processor for testing. */
@SupportedAnnotationTypes("com.google.j2cl.transpiler.TestAnnotation")
public class TestAptProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
    for (var element : roundEnv.getElementsAnnotatedWith(TestAnnotation.class)) {
      // Test that APT options are forwarded by J2CL.
      if (!processingEnv.getOptions().containsKey("TestAptProcessor.enabled")) {
        throw new RuntimeException("TestAptProcessor.enabled is not set");
      }

      var name = "Generated" + element.getSimpleName();
      var packageName =
          ((PackageElement) element.getEnclosingElement()).getQualifiedName().toString();

      writeSourceFile(
          packageName,
          name,
          """
          package %s;
          import jsinterop.annotations.JsMethod;
          // Generated by TestAptProcessor.java
          public class %s {
            @JsMethod
            public static native void foo();
          }
          """,
          packageName,
          name);

      writeResourceFile(packageName, name + ".native.js", "// Empty native.js file.");

      if (processingEnv.getOptions().containsKey("TestAptProcessor.generateJsSource")) {
        writeResourceFile(packageName, name + ".js", "// Plain .js file generated by APT.");
      }

      // Checked here: the action temp dir is deleted before the test can observe the file.
      if (processingEnv.getOptions().containsKey("TestAptProcessor.classOutputResource")) {
        writeClassOutputResource(element);
      }
    }
    return false;
  }

  @Override
  public SourceVersion getSupportedSourceVersion() {
    return SourceVersion.latestSupported();
  }

  @FormatMethod
  private void writeSourceFile(
      String packageName, String fileName, @FormatString String format, Object... args) {
    try {
      writeFile(
          processingEnv.getFiler().createSourceFile(packageName + "." + fileName), format, args);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  private void writeClassOutputResource(Element element) {
    try {
      // Empty package plus the annotated type is the JDK 18+ sibling-hint case.
      var file =
          processingEnv
              .getFiler()
              .createResource(
                  StandardLocation.CLASS_OUTPUT, "", "META-INF/example/config.json", element);
      var uri = file.toUri().toString();
      if (!uri.endsWith("/_sourcegen/META-INF/example/config.json")) {
        throw new RuntimeException(
            "CLASS_OUTPUT resource URI does not end with /_sourcegen/META-INF/example/config.json: "
                + uri);
      }
      var payload = "{\"example\":true}\n".getBytes(StandardCharsets.UTF_8);
      try (var out = file.openOutputStream()) {
        out.write(payload);
      }
      // Filer output objects cannot be reopened for reading; the file is on disk.
      var readBack = Files.readAllBytes(Path.of(file.toUri()));
      if (!Arrays.equals(payload, readBack)) {
        throw new RuntimeException("CLASS_OUTPUT resource payload mismatch for " + uri);
      }
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  @FormatMethod
  private void writeResourceFile(
      String packageName, String fileName, @FormatString String format, Object... args) {
    try {
      writeFile(
          processingEnv
              .getFiler()
              .createResource(StandardLocation.SOURCE_OUTPUT, packageName, fileName),
          format,
          args);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  @FormatMethod
  private static void writeFile(FileObject file, @FormatString String format, Object... args)
      throws IOException {
    try (var writer = file.openWriter()) {
      writer.write(String.format(format, args));
    }
  }
}
