workspace(name = "com_google_j2cl_samples_helloworld")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Load j2cl repository

local_repository(
    name = "com_google_j2cl",
    path = "../..",
)

# If you are not developping with J2CL, consider to use an http archive instead of a local
# repository
# TODO(dramaix): make that the default once j2cl is publicly released
# http_archive(
#     name = "com_google_j2cl",
#     strip_prefix = "j2cl-master",
#     url = "https://github.com/google/j2cl/archive/master.zip",
# )

load("@com_google_j2cl//build_defs:repository.bzl", "load_j2cl_repo_deps")
load_j2cl_repo_deps()

load("@com_google_j2cl//build_defs:rules.bzl", "setup_j2cl_workspace")
setup_j2cl_workspace()
