package(default_visibility = ["//junit/generator/javatests/com/google/j2cl/junit/integration:__subpackages__"])

# Apache2
licenses(["notice"])

java_library(
    name = "testlogger",
    srcs = glob(["*.java"]),
)
