# Description:
#  Every .bzl file must have a corresponding package.
#  This BUILD file does not need to do anything except exist.

package(default_visibility = [
    "//java/com/google/protobuf/contrib/gwt:__pkg__",
    "//:__subpackages__",
])

# Google owns the copyright
licenses(["unencumbered"])
