# Description:
#  Every .bzl file must have a corresponding package.
#  This BUILD file does not need to do anything except exist.

package(default_visibility = [
    "//:__subpackages__",
])

# Apache2
licenses(["notice"])
