package(
    default_applicable_licenses = ["//:j2cl_license"],
    default_visibility = ["//tools/javatests/com/google/j2cl/tools/rta:__subpackages__"],
    licenses = ["notice"],
)

java_library(
    name = "golden_file_tester_lib",
    testonly = True,
    srcs = ["GoldenFileTester.java"],
    deps = [
        "//third_party:guava",
        "//third_party:junit",
        "//third_party:truth",
    ],
)
