# Apache2
licenses(["notice"])

package(default_visibility = ["//tools/javatests/com/google/j2cl/tools/rta:__subpackages__"])

java_library(
    name = "golden_file_tester_lib",
    testonly = True,
    srcs = ["GoldenFileTester.java"],
    deps = [
        "//third_party/java/junit",
        "//third_party:guava",
        "//third_party:truth",
    ],
)
