load(":allowlists_test.bzl", "allowlists_test_suite")

package(
    default_applicable_licenses = ["//:j2cl_license"],
    licenses = ["reciprocal"],
)

allowlists_test_suite(
    name = "allowlists_test",
)
