# Apache2
licenses(["notice"])

java_test(
    name = "FrontendUtilsTest",
    srcs = ["FrontendUtilsTest.java"],
    deps = [
        "//third_party:junit",
        "//third_party:truth",
        "//transpiler/java/com/google/j2cl/frontend",
    ],
)
