/*
 * Copyright 2015 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.j2cl.ast;

/**
 * This class will be autogenerated by APT from JavaType
 */
public class VisitorJavaType {

  public static JavaType visit(Visitor visitor, JavaType type) {
    if (visitor.enterJavaType(type)) {
      type.enclosingType = VisitorTypeReference.visit(visitor, type.enclosingType);
      type.superType = VisitorTypeReference.visit(visitor, type.superType);
      type.superInterfaces = VisitorListTypeReference.visit(visitor, type.superInterfaces);
      type.selfReference = VisitorTypeReference.visit(visitor, type.selfReference);
      type.methods = VisitorListMethod.visit(visitor, type.methods);
    }
    visitor.exitJavaType(type);
    return type;
  }
}
