# Description:
#   Exists to provide a package for bzl files.

package(
    default_applicable_licenses = ["//:j2cl_license"],
    licenses = ["notice"],
)

package_group(
    name = "toolchain_users",
    packages = [
        "//build_defs/internal_do_not_use/...",
    ],
)
