/**
 * This file mocks the AnnotatedMethod class by creating
 * a constructor function with the same name.
 * The code generated by the converter will be able to
 * add functions to this prototype afterwards.
 */
var AnnotatedMethod = function() {};

