package(
    default_visibility = ["//transpiler/javatests/com/google/j2cl/transpiler/readable:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "conformance_proto",
    srcs = ["conformance_proto.txt"],
)
