# Apache2
licenses(["notice"])

package(default_visibility = ["//transpiler/javatests/com/google/j2cl/transpiler/readable:__subpackages__"])

filegroup(
    name = "conformance_proto",
    srcs = ["conformance_proto.txt"],
)
