package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

java_library(
    name = "tracking_interface",
    srcs = [
        "SourceInfo.java",
        "TracksSourceInfo.java",
    ],
    deps = [
        "//third_party/java_src/jscomp/java/com/google/debugging/sourcemap:shared",
    ],
)
