package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

java_library(
    name = "sourcemapsinterface",
    srcs =
        glob(["*.java"]),
    deps = [
        "//java/com/google/common/base",
        "//third_party/java/eclipse:eclipse-jdt-core",
    ],
)
