# Description:
#   j2cl/transpiler: Java to Closure style JS transpiler.

package(default_visibility = ["//:__subpackages__"])

# Google owns the copyright
licenses(["unencumbered"])

java_library(
    name = "transpiler",
    runtime_deps = ["//transpiler/java/com/google/j2cl/transpiler"],
)
