# Google owns the copyright
licenses(["unencumbered"])

js_library(
    name = "nativejs",
    srcs = [
        "native.js",
    ],
    deps = [
        "//javascript/closure:base",
    ],
)

js_library(
    name = "ajd",
    deps_mgmt = "closure",
    deps = [
        ":B",
    ],
)
