# Apache2
licenses(["notice"])

js_library(
    name = "nativejs",
    srcs = [
        "native1.js",
        "native2.js",
        "native3.js",
        "native4.js",
        "native5.js",
    ],
    deps = [
        "//javascript/closure:base",
    ],
)

js_library(
    name = "ajd",
    deps_mgmt = "closure",
    exports = [
        ":B",
    ],
)
