# Apache2
licenses(["notice"])

# TODO(b/38265473): Uncomment this when bug is resolved.
# ERROR: Source file "[blaze-out/gcc-4.X.Y-crosstool-v18-hybrid-grtev4-k8-fastbuild/genfiles/]third_party/java_src/j2cl/transpiler/javatests/com/google/j2cl/transpiler/buildtest/daggerdeps/c.js.zip!/c/DaggerC.java.js" requires namespace "a.A_Factory", but no file was found in the dependencies of this rule that provides the latter.
# j2cl_library(
#     name = "c",
#     srcs = ["C.java",],
#     js_deps_mgmt = "closure", # Turn on deps pruning.
#     deps = [
#         ":b",
#         "//third_party/java/dagger:dagger-j2cl",
#     ],
# )

# load("//tools/build_rules:build_test.bzl", "build_test")
# build_test(
#         name = "buildtest",
#         targets = [":c",],
# )
