load(
    "//transpiler/javatests/com/google/j2cl/integration:integration_test.bzl",
    "integration_test",
)

package(
    default_applicable_licenses = ["//:j2cl_license"],
    licenses = ["notice"],
)

integration_test(
    srcs = glob(["**/*.java"]),
    # TODO(b/423839177): Problem with package private field shadowing
    enable_kt = False,
)
