# Apache2
licenses(["notice"])

java_test(
    name = "BaseWorkerTest",
    srcs = ["BaseWorkerTest.java"],
    deps = [
        "//third_party/bazel/src/main/protobuf:worker_protocol_java_proto",
        "//third_party/java/junit",
        "//third_party/java/mockito",
        "//third_party/java/truth",
        "//transpiler/java/com/google/j2cl/bazel",
    ],
)
